
--Checks to see if we are doing first time run for box score
create procedure firstBox
as
select top 1 game_id, team_id from teamBox
go

--Checks to see if we need to update for any of games in last three days
create procedure checkBox
as
select g.date, t.game_id, t.team_id, t.points, t.atHome
from teamBox t inner join 
		game g on t.game_id = g.game_id
where g.date >= GETDATE() - 3
order by date desc, game_id desc
go

--If we need to update any, delete them now
create procedure deleteFirst @game_id int, @team_id int
as
delete from teamBox where game_id = @game_id and team_id = @team_id
delete from playerBox where game_id = @game_id and team_id = @team_id
go

--Insert Team BoxScores
create procedure teamBoxInsert
@game_id							int,
@team_id							int,
@atHome							int,
@matchup_id						int,
@points							int,
@pointsAgainst					int   ,
@q1Points						int,
@q1PointsAgainst					int,
@q2Points						int,
@q2PointsAgainst					int,
@q3Points						int,
@q3PointsAgainst					int,
@q4Points						int,
@q4PointsAgainst					int,
@otPoints						int,
@otPointsAgainst					int,
@assists							int   ,
@blocks							int   ,
@blocksReceived					int   ,
@fieldGoalsAttempted				int   ,
@fieldGoalsMade					int   ,
@fieldGoalsPercentage			float,
@foulsOffensive					int   ,
@foulsDrawn						int   ,
@foulsPersonal					int   ,
@foulsTechnical					int   ,
@freeThrowsAttempted				int   ,
@freeThrowsMade					int   ,
@freeThrowsPercentage			float,
@minus							float,
@minutes							varchar(30),
@minutesCalculated				varchar(30),
@plus							float,
@plusMinusPoints					float,
@pointsFastBreak					int   ,
@pointsInThePaint				int   ,
@pointsSecondChance				int   ,
@reboundsDefensive				int   ,
@reboundsOffensive				int   ,
@reboundsTotal					int   ,
@steals							int   ,
@threePointersAttempted			int   ,
@threePointersMade				int   ,
@threePointersPercentage			float,
@turnovers						int   ,
@twoPointersAttempted			int   ,
@twoPointersMade					int   ,
@twoPointersPercentage			float,
@assistsTurnoverRatio			float,
@benchPoints						int   ,
@biggestLead						int   ,
@biggestLeadScore				varchar(30),
@biggestScoringRun				int   ,
@biggestScoringRunScore			varchar(30),
@fastBreakPointsAttempted		int   ,
@fastBreakPointsMade				int   ,
@fastBreakPointsPercentage		float,
@fieldGoalsEffectiveAdjusted		float,
@foulsTeam						int   ,
@foulsTeamTechnical				int   ,
@leadChanges						int   ,
@pointsFromTurnovers				int   ,
@pointsInThePaintAttempted		int   ,
@pointsInThePaintMade			int   ,
@pointsInThePaintPercentage		float,
@reboundsPersonal				int   ,
@reboundsTeam					int   ,
@reboundsTeamDefensive			int   ,
@reboundsTeamOffensive			int   ,
@secondChancePointsAttempted		int   ,
@secondChancePointsMade			int   ,
@secondChancePointsPercentage	float,
@timeLeading						varchar(30),
@timesTied						int   ,
@trueShootingAttempts			float,
@trueShootingPercentage			float,
@turnoversTeam					int   ,
@turnoversTotal					int   
as
insert into teamBox values(
@game_id						,
@team_id						,
@atHome							,
@matchup_id						,
@points							,
@pointsAgainst					,
@q1Points						,
@q1PointsAgainst				,
@q2Points						,
@q2PointsAgainst				,
@q3Points						,
@q3PointsAgainst				,
@q4Points						,
@q4PointsAgainst				,
@otPoints						,
@otPointsAgainst				,
@assists						,
@blocks							,
@blocksReceived					,
@fieldGoalsAttempted			,
@fieldGoalsMade					,
@fieldGoalsPercentage			,
@foulsOffensive					,
@foulsDrawn						,
@foulsPersonal					,
@foulsTechnical					,
@freeThrowsAttempted			,
@freeThrowsMade					,
@freeThrowsPercentage			,
@minus							,
@minutes						,
@minutesCalculated				,
@plus							,
@plusMinusPoints				,
@pointsFastBreak				,
@pointsInThePaint				,
@pointsSecondChance				,
@reboundsDefensive				,
@reboundsOffensive				,
@reboundsTotal					,
@steals							,
@threePointersAttempted			,
@threePointersMade				,
@threePointersPercentage		,
@turnovers						,
@twoPointersAttempted			,
@twoPointersMade				,
@twoPointersPercentage			,
@assistsTurnoverRatio			,
@benchPoints					,
@biggestLead					,
@biggestLeadScore				,
@biggestScoringRun				,
@biggestScoringRunScore			,
@fastBreakPointsAttempted		,
@fastBreakPointsMade			,
@fastBreakPointsPercentage		,
@fieldGoalsEffectiveAdjusted	,
@foulsTeam						,
@foulsTeamTechnical				,
@leadChanges					,
@pointsFromTurnovers			,
@pointsInThePaintAttempted		,
@pointsInThePaintMade			,
@pointsInThePaintPercentage		,
@reboundsPersonal				,
@reboundsTeam					,
@reboundsTeamDefensive			,
@reboundsTeamOffensive			,
@secondChancePointsAttempted	,
@secondChancePointsMade			,
@secondChancePointsPercentage	,
@timeLeading					,
@timesTied						,
@trueShootingAttempts			,
@trueShootingPercentage			,
@turnoversTeam					,
@turnoversTotal					)
go

--Insert Player BoxScores

create procedure playerBoxInsert
@game_id						int,
@team_id						int,
@player_id						int,
@status							varchar(30),
@starter						int,
@position						varchar(2),
@points							int,
@assists						int   ,
@blocks							int   ,
@blocksReceived					int   ,
@fieldGoalsAttempted			int   ,
@fieldGoalsMade					int   ,
@fieldGoalsPercentage			float,
@foulsOffensive					int   ,
@foulsDrawn						int   ,
@foulsPersonal					int   ,
@foulsTechnical					int   ,
@freeThrowsAttempted			int   ,
@freeThrowsMade					int   ,
@freeThrowsPercentage			float,
@minus							float,
@minutes						varchar(30),
@minutesCalculated				varchar(30),
@plus							float,
@plusMinusPoints				float,
@pointsFastBreak				int   ,
@pointsInThePaint				int   ,
@pointsSecondChance				int   ,
@reboundsDefensive				int   ,
@reboundsOffensive				int   ,
@reboundsTotal					int   ,
@steals							int   ,
@threePointersAttempted			int   ,
@threePointersMade				int   ,
@threePointersPercentage		float,
@turnovers						int   ,
@twoPointersAttempted			int   ,
@twoPointersMade				int   ,
@twoPointersPercentage			float,
@statusReason					varchar(100),
@statusDescription				varchar(200)
as
insert into playerBox values(
@game_id						,
@team_id						,
@player_id						,
@status							,
@starter						,
@position						,
@points							,
@assists						,
@blocks							,
@blocksReceived					,
@fieldGoalsAttempted			,
@fieldGoalsMade					,
@fieldGoalsPercentage			,
@foulsOffensive					,
@foulsDrawn						,
@foulsPersonal					,
@foulsTechnical					,
@freeThrowsAttempted			,
@freeThrowsMade					,
@freeThrowsPercentage			,
@minus							,
@minutes						,
@minutesCalculated				,
@plus							,
@plusMinusPoints				,
@pointsFastBreak				,
@pointsInThePaint				,
@pointsSecondChance				,
@reboundsDefensive				,
@reboundsOffensive				,
@reboundsTotal					,
@steals							,
@threePointersAttempted			,
@threePointersMade				,
@threePointersPercentage		,
@turnovers						,
@twoPointersAttempted			,
@twoPointersMade				,
@twoPointersPercentage			,
@statusReason					,
@statusDescription				)
go

--Check the last box we have after deleting
--Not sure if redundant at the moment
create procedure lastBox
as 
select top 1 * 
from teamBox 
order by date desc, game_id desc
go
